### ISSUE TITLE
matomo vhost not in the repo

### ISSUE THREAD

**Issue by rgaudin** [kiwix/maintenance#123]
The [matomo compose](/maintenance/blob/master/matomo-server-docker/docker-compose.yml) mounts a folder as `/etc/nginx/conf.d` but this folder's content is not specified in the repo.

This means that the recipe is not working as-is.

``` yaml
  web:
    image: nginx:latest
    container_name: matomo_web
    volumes:
      - "appdir:/var/www/html"
      - "/data/matomo/data:/var/www/html/misc/user"
      - "/data/matomo/web/conf:/etc/nginx/conf.d"
```

I believe the `matomo.conf` file that sits in this folder should be included in the repo so that we can easily recover from a server failure.

Current content:
``` nginx
server {

  listen [::]:80;
  listen 80;

  server_name stats.kiwix.org;
  root /var/www/html/;
  index index.php;

  location ~ ^/(index|matomo|piwik|js/index).php {
        fastcgi_pass matomo_app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_read_timeout 600;
  }

  location ~* ^.+\.php$ {
    deny all;
    return 403;
  }

  location / {
    try_files $uri $uri/ =404;
  }

  location ~ /(config|tmp|core|lang) {
    deny all;
    return 403;
  }

  location ~ \.(gif|ico|jpg|png|svg|js|css|htm|html|mp3|mp4|wav|ogg|avi|ttf|eot|woff|woff2|json)$ {
    allow all;
  }

  location ~ /(libs|vendor|plugins|misc/user) {
    deny all;
    return 403;
  }

}
```
